name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  ci:

    runs-on: ubuntu-latest
    env:
      working-directory: ./src

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.*

    - name: Build and Test
      run: dotnet test
      working-directory: ${{env.working-directory}}


