name: CI

on:
  push:
    branches: [ main ]

jobs:
  ci:

    runs-on: ubuntu-latest
    env:
      working-directory: ./src

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.*

    - name: Install dependencies      
      run: dotnet restore
      working-directory: ${{env.working-directory}}
    - name: Build     
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{env.working-directory}}
    - name: Test
      run: dotnet test --no-restore
      working-directory: ${{env.working-directory}}


