name: Nuget Publish

on:
  workflow_dispatch:

jobs:
  nuget_publish:

    runs-on: ubuntu-latest
    env:
      working-directory: ./src

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.*

    - name: Build and Test
      run: dotnet test -c Release
      working-directory: ${{env.working-directory}}

    - name: pack package
      run: dotnet pack -c Release
      working-directory: ${{env.working-directory}}

    - name: Publish NuGet
      run: dotnet nuget push **/*.snupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGETKEY }} --skip-duplicate
      working-directory: ${{env.working-directory}}
          


